# POWER-TRIMS Configuration

# This file contains the configuration for the PowerTrims plugin.

# You can modify the values here to change the behavior of the trims.

# To reload the configuration, use the command /powertrims reload, right now using reload command
# only affects enable and disabling of trims, to change the ability values restart the server

# Global settings for enabling or disabling entire trim powers.
trims:
  sentry: true
  silence: true
  vex: true
  ward: true
  wild: true
  coast: true
  dune: true
  eye: true
  host: true
  raiser: true
  rib: true
  snout: true
  spire: true
  tide: true
  wayfinder: true
  flow: true

cooldown-display: SCOREBOARD  # Options: SCOREBOARD, ACTION_BAR. Default is Scoreboard

  # POWER-TRIMS Configuration
sentry:
  primary:
    arrow_count: 3
    spread: 0.15
    cooldown: 90000
    true_damage: 0.5
silence:
  primary:
    radius: 15.0
    potion_duration_ticks: 400
    pearl_cooldown_ticks: 200
    max_affected_entities: 30
    cooldown: 90000
  passive:
    cooldown: 120000
    echo_radius: 6.0
    effect_duration_ticks: 300
vex:
  primary:
    cooldown: 120000
    radius: 30.0
    damage: 8.0
    debuff_duration_ticks: 400
    blindness_duration_ticks: 100
  passive:
    cooldown: 120000
    hide_duration_ticks: 200
    health_threshold: 8.0
ward:
  primary:
    barrier_duration: 200
    absorption_level: 4
    resistance_boost_level: 2
    cooldown: 120000
wild:
  primary:
    cooldown: 20000
    poison_duration_ticks: 200
    grapple_range: 60.0
    grapple_speed: 1.8
  passive:
    cooldown_seconds: 20
    trigger_health: 8
    root_trap_radius_xz: 5.0
    root_trap_radius_y: 3.0
    root_trap_duration_ticks: 200
coast:
  primary:
    water-burst-radius: 30
    water-burst-damage: 10
    water-burst-cooldown: 60000
    pull-duration-ticks: 60
    debuff-duration-ticks: 80
    buff-duration-ticks: 100
    weakness-amplifier: 1
    slowness-amplifier: 1
    speed-amplifier: 1
    resistance-amplifier: 0
dune:
  primary:
    sandstorm_radius: 12
    sandstorm_damage: 10
    cooldown: 60000
eye:
  primary:
    true_sight_radius: 80.0
    true_sight_duration_ticks: 600
    cooldown: 120000
    task_interval_ticks: 20
    true_sight_vertical_radius: 50.0
host:
  primary:
    cooldown: 120000
    effect_steal_radius: 10.0
    health_steal_amount: 4.0
    particle_density: 4.0
raiser:
  primary:
    cooldown: 120000
    entity_pull_radius: 15.0
    player_upward_boost: 1.5
    pearl_cooldown_ticks: 200
rib:
  primary:
    cooldown: 60000
    minion_lifespan_ticks: 1200
snout:
  primary:
    cooldown: 120000
    minion_lifespan_ticks: 1800
spire:
  primary:
    dash_distance: 8.0
    dash_speed: 2.0
    knockback_strength: 1.5
    slow_duration: 60
    vulnerable_duration: 100
    damage_amplification: 0.6
    cooldown: 30000
tide:
  primary:
    cooldown: 120000
    wave_width: 3.0
    effect_duration_ticks: 300
    knockback_strength: 1.8
    wall_height: 6
    move_delay_ticks: 2
    max_moves: 20
wayfinder:
  primary:
    cooldown: 120000
flow:
  primary:
    heart_cost_interval: 20
    heart_cost_amount: 2.0
    cooldown: 60000
    duration: 400
