name: PowerTrims
version: '1.0'
main: MCplugin.powerTrims.PowerTrimss
api-version: '1.21'
author: div

commands:
  trust:
    description: Trust a player, preventing your abilities from affecting them.
    usage: /<command> <player name>
  untrust:
    description: Remove trust from a player, allowing your abilities to affect them.
    usage: /<command> <player name>
  trustlist:
    description: View your list of trusted players.
    usage: /<command>

